apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-02-04T03:48:22Z"
  name: simplenode-canary
  resourceVersion: "82163"
  selfLink: /api/v1/namespaces/simpleproject-staging/services/simplenode
  uid: 3086400b-4701-11ea-93cb-42010aa800b9
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simplenode
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
