apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: simplenode
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - simplenode.simpleproject-dev.34.94.234.203.xip.io
  - simplenode
  http:
  - route:
    - destination:
        host: simplenode.simpleproject-dev.svc.cluster.local
